"""
Spontaneous activity controls for the LMI participation rate analysis.

Three analyses using the per-cell data CSV generated by
plot_participation_vs_transient_lmi (reactivation_lmi_prediction pipeline):

1. Transient frequency vs LMI boxplot: mean spontaneous activity per LMI bin,
   R+ and R- panels. Tests whether LMI correlates with spontaneous activity.
2. Partial correlation: LMI vs participation rate, raw and after controlling
   for transient frequency. Tests whether spontaneous activity explains the
   LMI–participation relationship.
3. Temporal evolution of residual participation rate: mirrors the
   temporal_evolution_per_mouse.svg figure but with participation rates
   residualised on spontaneous transient frequency.
"""

import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr, linregress, ttest_rel

sys.path.append(r'/home/aprenard/repos/NWB_analysis')
sys.path.append(r'/home/aprenard/repos/fast-learning')
import src.utils.utils_io as io
from src.utils.utils_plot import *


# ============================================================================
# PARAMETERS
# ============================================================================

save_dir = os.path.join(io.results_dir, 'reactivation')
lmi_data_csv = os.path.join(save_dir, 'participation_vs_transient_lmi_day0_data.csv')

_reactivation_lmi_dir = io.adjust_path_to_host(
    '/mnt/lsens-analysis/Anthony_Renard/analysis_output/fast-learning/reactivation_lmi'
)
participation_csv = os.path.join(_reactivation_lmi_dir, 'cell_participation_rates_per_day.csv')

os.makedirs(save_dir, exist_ok=True)


# ============================================================================
# ANALYSIS 1: TRANSIENT FREQUENCY vs LMI BOXPLOT
# ============================================================================

def plot_transient_freq_vs_lmi_histogram(data_csv_path, save_path):
    """
    Boxplot: transient frequency (day 0) per LMI bin, one panel for R+ and R-.

    If transient_freq tracks LMI (positive slope), it would suggest that the
    participation–LMI relationship is confounded by spontaneous activity.

    Parameters
    ----------
    data_csv_path : str
        Path to the _data.csv saved by plot_participation_vs_transient_lmi.
    save_path : str
        Path to save SVG file.
    """
    if not os.path.exists(data_csv_path):
        print(f"  Warning: Data CSV not found: {data_csv_path}")
        return None

    merged = pd.read_csv(data_csv_path)
    merged = merged.dropna(subset=['lmi', 'transient_freq', 'reward_group'])

    lmi_bins = np.arange(-1.0, 1.2, 0.2)
    # Show full interval for each bin, e.g. "−1.0–−0.8"
    bin_labels = [f'{lmi_bins[k]:.1f}–{lmi_bins[k+1]:.1f}' for k in range(len(lmi_bins) - 1)]
    # Position of the LMI=0 boundary: between bin index 4 ([−0.2,0)) and 5 ([0,0.2))
    zero_boundary = 4.5

    group_colors = {'R+': reward_palette[1], 'R-': reward_palette[0]}

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    for i, reward_group in enumerate(['R+', 'R-']):
        ax = axes[i]
        gdata = merged[merged['reward_group'] == reward_group].copy()

        if len(gdata) < 3:
            ax.text(0.5, 0.5, f'Insufficient data\n(n={len(gdata)})',
                    ha='center', va='center', transform=ax.transAxes, fontsize=12)
            ax.set_title(reward_group, fontweight='bold', fontsize=14)
            continue

        gdata['lmi_bin'] = pd.cut(
            gdata['lmi'], bins=lmi_bins, labels=bin_labels, include_lowest=True
        )

        sns.boxplot(
            data=gdata, x='lmi_bin', y='transient_freq',
            color=group_colors[reward_group], ax=ax,
            showfliers=False, linewidth=0.8
        )

        # Mark LMI = 0 boundary
        ax.axvline(zero_boundary, color='black', linestyle='--', linewidth=0.8, alpha=0.5)

        x = gdata['lmi'].values
        y = gdata['transient_freq'].values
        r, p = pearsonr(x, y)

        if p < 0.001:
            p_str = 'p < 0.001 ***'
        elif p < 0.01:
            p_str = f'p = {p:.3f} **'
        elif p < 0.05:
            p_str = f'p = {p:.3f} *'
        else:
            p_str = f'p = {p:.3f} ns'

        n_mice = gdata['mouse_id'].nunique()
        ax.text(0.05, 0.95,
                f'n = {len(x)} cells, {n_mice} mice\nPearson r = {r:.3f}\n{p_str}',
                transform=ax.transAxes, fontsize=10, va='top',
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.9, edgecolor='gray'))

        ax.set_xlabel('LMI bin', fontweight='bold', fontsize=12)
        ax.set_ylabel('Transient frequency (events/min)' if i == 0 else '',
                      fontweight='bold', fontsize=12)
        ax.set_title(f'{reward_group}', fontweight='bold', fontsize=14)
        ax.tick_params(axis='x', rotation=45)
        ax.grid(True, alpha=0.3, axis='y')
        print(f"  {reward_group}: r={r:.3f}, p={p:.4f}, n={len(x)} cells, {n_mice} mice")

    fig.suptitle('Spontaneous Transient Frequency vs LMI (Day 0)',
                 fontsize=13, fontweight='bold')
    sns.despine()
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, format='svg', dpi=300, bbox_inches='tight')
        print(f"  Saved: {save_path}")

    return fig


# ============================================================================
# ANALYSIS 2: PARTIAL CORRELATION — LMI vs PARTICIPATION CONTROLLING FOR
#             TRANSIENT FREQUENCY
# ============================================================================

def _partial_corr(x, y, z):
    """
    Pearson partial correlation of x and y, controlling for z.
    Residualises both x and y on z via linear regression, then correlates residuals.
    Returns (r, p).
    """
    def residuals(a, b):
        slope, intercept, _, _, _ = linregress(b, a)
        return a - (slope * b + intercept)

    rx = residuals(x, z)
    ry = residuals(y, z)
    return pearsonr(rx, ry)


def plot_partial_correlation_lmi_participation(data_csv_path, save_path):
    """
    Added-variable (partial regression) scatter plots comparing the raw and
    partial relationship between LMI and participation rate.

    Layout: 2 rows (R+, R-) × 2 columns (raw, partial).
    - Left column: raw scatter of LMI vs participation_rate.
    - Right column: partial scatter — residuals of LMI and participation_rate
      after each is regressed on transient_freq. The slope and r of these
      residuals equal the partial regression coefficient and partial correlation.

    If the partial r (right column) remains significant and close in magnitude
    to the raw r (left column), spontaneous activity does not explain the
    LMI–participation relationship.

    Parameters
    ----------
    data_csv_path : str
        Path to the _data.csv saved by plot_participation_vs_transient_lmi.
    save_path : str
        Path to save SVG file.
    """
    if not os.path.exists(data_csv_path):
        print(f"  Warning: Data CSV not found: {data_csv_path}")
        return None

    merged = pd.read_csv(data_csv_path)
    merged = merged.dropna(subset=['lmi', 'participation_rate', 'transient_freq', 'reward_group'])

    def residuals(a, b):
        slope, intercept, _, _, _ = linregress(b, a)
        return a - (slope * b + intercept)

    def annotate(ax, r, p):
        p_str = ('p < 0.001 ***' if p < 0.001 else
                 f'p = {p:.3f} **' if p < 0.01 else
                 f'p = {p:.3f} *' if p < 0.05 else
                 f'p = {p:.3f} ns')
        ax.text(0.05, 0.95, f'r = {r:.3f}\n{p_str}',
                transform=ax.transAxes, fontsize=10, va='top',
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.9, edgecolor='gray'))

    fig, axes = plt.subplots(2, 2, figsize=(12, 10))

    for row, reward_group in enumerate(['R+', 'R-']):
        color = reward_palette[1] if reward_group == 'R+' else reward_palette[0]
        gdata = merged[merged['reward_group'] == reward_group]

        if len(gdata) < 5:
            for col in range(2):
                axes[row, col].text(0.5, 0.5, 'Insufficient data',
                                    ha='center', va='center',
                                    transform=axes[row, col].transAxes)
            continue

        lmi = gdata['lmi'].values
        part = gdata['participation_rate'].values
        freq = gdata['transient_freq'].values

        lmi_resid = residuals(lmi, freq)
        part_resid = residuals(part, freq)

        r_raw, p_raw = pearsonr(lmi, part)
        r_partial, p_partial = pearsonr(lmi_resid, part_resid)

        print(f"  {reward_group}  raw r={r_raw:.3f} p={p_raw:.4f} | "
              f"partial r={r_partial:.3f} p={p_partial:.4f}  (n={len(lmi)} cells)")

        for col, (x, y, r, p, xlabel, ylabel) in enumerate([
            (lmi,       part,       r_raw,     p_raw,
             'LMI', 'Participation rate'),
            (lmi_resid, part_resid, r_partial, p_partial,
             'LMI  (residual | transient freq)',
             'Participation rate  (residual | transient freq)'),
        ]):
            ax = axes[row, col]
            ax.scatter(x, y, color=color, alpha=0.3, s=10, linewidths=0)

            slope, intercept, _, _, _ = linregress(x, y)
            x_range = np.linspace(x.min(), x.max(), 100)
            ax.plot(x_range, slope * x_range + intercept,
                    color='black', linewidth=1.5)

            ax.axvline(0, color='gray', linestyle='--', linewidth=0.7, alpha=0.5)
            ax.axhline(0, color='gray', linestyle='--', linewidth=0.7, alpha=0.5)
            annotate(ax, r, p)

            ax.set_xlabel(xlabel, fontsize=11)
            ax.set_ylabel(ylabel if col == 0 else '', fontsize=11)
            title = ('Raw' if col == 0 else 'Partial  (ctrl transient freq)')
            n_mice = gdata['mouse_id'].nunique()
            ax.set_title(f'{reward_group} — {title}  (n={len(lmi)} cells, {n_mice} mice)',
                         fontweight='bold', fontsize=12)
            ax.grid(True, alpha=0.3)

    fig.suptitle('LMI vs Participation Rate: Raw and Partial Correlation (Day 0)',
                 fontsize=13, fontweight='bold')
    sns.despine()
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, format='svg', dpi=300, bbox_inches='tight')
        print(f"  Saved: {save_path}")

    return fig


# ============================================================================
# ANALYSIS 3: TEMPORAL EVOLUTION WITH RESIDUAL PARTICIPATION RATE
# ============================================================================

def plot_temporal_evolution_residual(participation_csv, lmi_data_csv, save_path=None):
    """
    Temporal evolution of LMI+ vs LMI- participation rates across days,
    shown raw and after controlling for spontaneous transient frequency.

    Layout: 2 rows × 2 columns.
      Top row    : raw participation rate (mirrors temporal_evolution_per_mouse.svg)
      Bottom row : residual participation rate — linear contribution of transient_freq
                   removed (regression fitted on day-0 data per reward group, then
                   applied across all days using each cell's fixed transient_freq)
      Columns    : R+ (left), R- (right)

    Per-day paired t-tests (LMI+ vs LMI-) are printed and displayed for both
    raw and residual rows.

    Parameters
    ----------
    participation_csv : str
        Path to cell_participation_rates_per_day.csv.
    lmi_data_csv : str
        Path to participation_vs_transient_lmi_day0_data.csv
        (contains transient_freq, lmi, lmi_p, reward_group per cell).
    save_path : str or None
        Path to save SVG file.
    """
    for path, label in [(participation_csv, 'Participation CSV'),
                        (lmi_data_csv, 'LMI data CSV')]:
        if not os.path.exists(path):
            print(f"  Warning: {label} not found: {path}")
            return None

    # --- Load data ---
    participation_df = pd.read_csv(participation_csv)
    day0_df = pd.read_csv(lmi_data_csv).dropna(
        subset=['lmi', 'lmi_p', 'transient_freq', 'reward_group']
    )

    # Assign LMI category using the same thresholds as reactivation_lmi_prediction.py
    day0_df['lmi_category'] = 'neutral'
    day0_df.loc[day0_df['lmi_p'] >= 0.975, 'lmi_category'] = 'positive'
    day0_df.loc[day0_df['lmi_p'] <= 0.025, 'lmi_category'] = 'negative'
    day0_df = day0_df[day0_df['lmi_category'].isin(['positive', 'negative'])]

    # Merge all-days participation with cell info from day 0
    cell_info = day0_df[['mouse_id', 'roi', 'lmi_category', 'reward_group', 'transient_freq']]
    merged = pd.merge(participation_df, cell_info, on=['mouse_id', 'roi'], how='inner')

    # --- Residualise participation on transient_freq ---
    # Fit regression on day-0 data per reward group; apply across all days
    # (transient_freq is treated as a fixed per-cell covariate)
    merged['participation_resid'] = np.nan
    for rg in ['R+', 'R-']:
        day0_mask = (merged['day'] == 0) & (merged['reward_group'] == rg)
        d0 = merged[day0_mask]
        if len(d0) < 5:
            continue
        slope, intercept, _, _, _ = linregress(
            d0['transient_freq'].values, d0['participation_rate'].values
        )
        print(f"  {rg} residualisation: slope={slope:.4f}, intercept={intercept:.4f} "
              f"(n={len(d0)} cells on day 0)")
        grp_mask = merged['reward_group'] == rg
        merged.loc[grp_mask, 'participation_resid'] = (
            merged.loc[grp_mask, 'participation_rate']
            - (slope * merged.loc[grp_mask, 'transient_freq'] + intercept)
        )

    # --- Aggregate to per-mouse per-day means ---
    days_list = [-2, -1, 0, 1, 2]
    lmi_categories = ['positive', 'negative']
    reward_groups = ['R+', 'R-']
    colors = {'positive': '#d62728', 'negative': '#1f77b4'}

    def _aggregate(df, metric):
        records = []
        for rg in reward_groups:
            for lmi_cat in lmi_categories:
                mask = (df['reward_group'] == rg) & (df['lmi_category'] == lmi_cat)
                cells = df[mask][['mouse_id', 'roi']].drop_duplicates()
                for mouse_id in cells['mouse_id'].unique():
                    mouse_rois = cells[cells['mouse_id'] == mouse_id]['roi'].values
                    for day in days_list:
                        day_mask = (
                            (df['mouse_id'] == mouse_id) &
                            (df['roi'].isin(mouse_rois)) &
                            (df['day'] == day)
                        )
                        vals = df[day_mask][metric].dropna().values
                        records.append({
                            'reward_group': rg,
                            'lmi_category': lmi_cat,
                            'mouse_id': mouse_id,
                            'day': day,
                            'value': np.mean(vals) if len(vals) > 0 else np.nan
                        })
        return pd.DataFrame(records)

    df_raw = _aggregate(merged, 'participation_rate')
    df_resid = _aggregate(merged, 'participation_resid')

    # --- Per-day paired t-tests (LMI+ vs LMI-) ---
    def _posthoc(df_agg, rg, label):
        df_rg = df_agg[df_agg['reward_group'] == rg]
        df_pos = df_rg[df_rg['lmi_category'] == 'positive']
        df_neg = df_rg[df_rg['lmi_category'] == 'negative']
        results = {d: {'p': np.nan, 'significant': False} for d in days_list}

        print(f"\n  {rg} [{label}] paired t-tests (LMI+ vs LMI-):")
        for day in days_list:
            pos_d = df_pos[df_pos['day'] == day]
            neg_d = df_neg[df_neg['day'] == day]
            mice_both = sorted(set(pos_d['mouse_id']) & set(neg_d['mouse_id']))
            if len(mice_both) >= 3:
                pos_v = [pos_d[pos_d['mouse_id'] == m]['value'].values[0]
                         for m in mice_both]
                neg_v = [neg_d[neg_d['mouse_id'] == m]['value'].values[0]
                         for m in mice_both]
                try:
                    _, p = ttest_rel(pos_v, neg_v)
                    sig = ('***' if p < 0.001 else '**' if p < 0.01
                           else '*' if p < 0.05 else 'ns')
                    results[day] = {'p': p, 'significant': p < 0.05}
                    print(f"    Day {day:+2d}: n={len(mice_both)} mice, p={p:.4f} {sig}")
                except Exception:
                    print(f"    Day {day:+2d}: test failed")
            else:
                print(f"    Day {day:+2d}: insufficient paired data (n={len(mice_both)})")
        return results

    # --- Plot ---
    row_configs = [
        (df_raw,   'Participation rate',                              'Raw'),
        (df_resid, 'Residual participation rate\n(ctrl transient freq)', 'Residual'),
    ]

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    for row, (df_agg, ylabel, row_label) in enumerate(row_configs):
        for col, rg in enumerate(reward_groups):
            ax = axes[row, col]
            df_rg = df_agg[df_agg['reward_group'] == rg].dropna(subset=['value'])
            posthoc = _posthoc(df_agg, rg, row_label)

            # Seaborn barplot: mean ± 95% CI, no end caps on error bars
            sns.barplot(
                data=df_rg, x='day', y='value', hue='lmi_category',
                hue_order=lmi_categories, palette=colors, order=days_list,
                estimator=np.mean, errorbar=('ci', 95), capsize=0,
                err_kws={'linewidth': 1.5}, ax=ax
            )
            for patch in ax.patches:
                patch.set_alpha(0.7)
                patch.set_edgecolor('black')
                patch.set_linewidth(0.8)

            # Individual mouse trajectories, using bar centers from ax.containers
            for j, lmi_cat in enumerate(lmi_categories):
                if j >= len(ax.containers):
                    continue
                cat_data = df_rg[df_rg['lmi_category'] == lmi_cat]
                x_centers = {days_list[k]: bar.get_x() + bar.get_width() / 2
                             for k, bar in enumerate(ax.containers[j])}
                for mouse_id in cat_data['mouse_id'].unique():
                    mdata = cat_data[cat_data['mouse_id'] == mouse_id].sort_values('day')
                    mx = [x_centers[d] for d in mdata['day'] if d in x_centers]
                    my = mdata['value'].values
                    ax.plot(mx, my, '-', color=colors[lmi_cat],
                            linewidth=0.8, alpha=0.4, zorder=5)

            # Fix y-axis for raw row to match original figure
            if row == 0:
                ax.set_ylim(0, 0.6)

            # Significance markers
            y_sig = ax.get_ylim()[1] * 0.92
            for k, day in enumerate(days_list):
                p_val = posthoc[day]['p']
                if not np.isnan(p_val) and p_val < 0.05:
                    sig = '***' if p_val < 0.001 else '**' if p_val < 0.01 else '*'
                    x0 = ax.containers[0][k].get_x() + ax.containers[0][k].get_width() / 2
                    x1 = ax.containers[1][k].get_x() + ax.containers[1][k].get_width() / 2
                    ax.text((x0 + x1) / 2, y_sig, sig,
                            ha='center', va='bottom', fontsize=12, fontweight='bold')

            ax.set_xlabel('Day', fontweight='bold', fontsize=12)
            ax.set_ylabel(ylabel, fontweight='bold', fontsize=11)
            ax.set_title(f'{rg} Mice — {row_label}', fontweight='bold', fontsize=13)
            handles, labels = ax.get_legend_handles_labels()
            ax.legend(handles, [f'{l.capitalize()} LMI' for l in labels],
                      loc='best', fontsize=10)
            ax.grid(True, alpha=0.3, axis='y')
            sns.despine(ax=ax)

    fig.suptitle(
        'Temporal Evolution: LMI+ vs LMI- Participation Rate\n(Raw and Residual)',
        fontsize=13, fontweight='bold'
    )
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, format='svg', dpi=300, bbox_inches='tight')
        print(f"\n  Saved: {save_path}")

    return fig


# ============================================================================
# MAIN EXECUTION
# ============================================================================

print("\n" + "="*60)
print("ANALYSIS 1: TRANSIENT FREQUENCY vs LMI BOXPLOT")
print("="*60)

svg_path = os.path.join(save_dir, 'transient_freq_vs_lmi_histogram_day0.svg')
print(f"\nPlotting transient frequency vs LMI (Day 0)...")
plot_transient_freq_vs_lmi_histogram(lmi_data_csv, svg_path)

print("\n" + "="*60)
print("ANALYSIS 2: PARTIAL CORRELATION — LMI vs PARTICIPATION | TRANSIENT FREQ")
print("="*60)

svg_path = os.path.join(save_dir, 'partial_corr_lmi_participation_day0.svg')
print(f"\nPartial correlation: LMI vs participation rate, controlling for transient freq...")
plot_partial_correlation_lmi_participation(lmi_data_csv, svg_path)

print("\n" + "="*60)
print("ANALYSIS 3: TEMPORAL EVOLUTION WITH RESIDUAL PARTICIPATION RATE")
print("="*60)

svg_path = os.path.join(save_dir, 'temporal_evolution_residual_participation_day0.svg')
print(f"\nTemporal evolution: raw vs residual participation rate across days...")
plot_temporal_evolution_residual(participation_csv, lmi_data_csv, svg_path)

print("\n" + "="*60)
print("DONE")
print("="*60)
print(f"\nResults saved to: {save_dir}")
